# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of your application code
COPY server ./

# Expose the port your Express.js app is running on
EXPOSE 8000

# Start the Express.js server
CMD ["npm", "start"]
