# fly.toml app configuration file generated for sponsify on 2023-09-18T17:31:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sponsify"
primary_region = "lhr"

[build]
  image = "rgraner/sponsify-frontend:latest"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = ""
  internal_port = 3000

[[services]]
  protocol = ""
  internal_port = 8000
